// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxLhN2q3P6CDju2lyr9or6IWA99ABJ_cs',
    appId: '1:659192666885:web:d5809e7040cfeb2551b56c',
    messagingSenderId: '659192666885',
    projectId: 'indian-cultures',
    authDomain: 'indian-cultures.firebaseapp.com',
    storageBucket: 'indian-cultures.appspot.com',
    measurementId: 'G-XF3G37NZ69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnxpINYWfWlWL1ku7tGRF40U5XLHxLP8Y',
    appId: '1:659192666885:android:8970837994eea9e151b56c',
    messagingSenderId: '659192666885',
    projectId: 'indian-cultures',
    storageBucket: 'indian-cultures.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSNabYNXCHcVqjPdYPkQxnF91JKDM9ciE',
    appId: '1:659192666885:ios:41a17d5ca347507451b56c',
    messagingSenderId: '659192666885',
    projectId: 'indian-cultures',
    storageBucket: 'indian-cultures.appspot.com',
    iosBundleId: 'com.king.indianCultures',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSNabYNXCHcVqjPdYPkQxnF91JKDM9ciE',
    appId: '1:659192666885:ios:868a2d695cde210e51b56c',
    messagingSenderId: '659192666885',
    projectId: 'indian-cultures',
    storageBucket: 'indian-cultures.appspot.com',
    iosBundleId: 'com.king.indianCultures.RunnerTests',
  );
}
